# Generated by Django 5.2.17 on 2026-09-22 16:05

import django.db.models.deletion
import uuid
import work_items.domain.status
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('ANALYSING', 'Analysing'), ('READY_FOR_REVIEW', 'Ready For Review'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], db_index=True, default=work_items.domain.status.WorkItemStatus['RECEIVED'], max_length=32)),
                ('category', models.CharField(blank=True, max_length=32, null=True)),
                ('priority', models.CharField(blank=True, max_length=16, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('analysis_model', models.CharField(blank=True, max_length=100, null=True)),
                ('analysed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='work_item_status_created')],
                'constraints': [models.UniqueConstraint(fields=('external_id',), name='uniq_work_item_external_id'), models.CheckConstraint(condition=models.Q(('status__in', ['RECEIVED', 'ANALYSING', 'READY_FOR_REVIEW', 'FAILED', 'COMPLETED'])), name='work_item_valid_status'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', [work_items.domain.status.WorkItemStatus['READY_FOR_REVIEW'], work_items.domain.status.WorkItemStatus['COMPLETED']]), _negated=True), models.Q(('category__isnull', False), ('priority__isnull', False), ('recommended_action__isnull', False), ('summary__isnull', False)), _connector='OR'), name='work_item_reviewable_has_analysis')],
            },
        ),
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('actor', models.CharField(choices=[('system', 'System'), ('operator', 'Operator')], max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='work_items.workitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['work_item', '-created_at'], name='transition_item_created')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveIntegerField()),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(max_length=20)),
                ('outcome', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('raw_output', models.TextField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='work_items.workitem')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['work_item', '-started_at'], name='attempt_item_started')],
                'constraints': [models.UniqueConstraint(fields=('work_item', 'attempt_no'), name='uniq_attempt_no_per_work_item')],
            },
        ),
    ]
